packaging_format = 2

id = "phpbb"
name = "phpBB"
description.en = "Forum software that is easy to use, powerful, and highly customisable"
description.fr = "Forum facile à utiliser, puissant et hautement personnalisable"

version = "3.3.11~ynh2"

maintainers = []

[upstream]
license = "GPL-2.0-only"
website = "http://www.phpbb.com/"
demo = "https://www.phpbb.com/demo/"
admindoc = "https://www.phpbb.com/support/docs/"
code = "https://github.com/phpbb/phpbb"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpbb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://download.phpbb.com/pub/release/3.3/3.3.11/phpBB-3.3.11.zip"
        sha256 = "02006f09d71c44de55044497ef8633f95c6103361d175c816015280f3bcfe87b"

        [resources.sources.fr]
        url = "https://github.com/qiaeru/phpbb-language-fr/archive/refs/tags/v4.11.0.zip"
        sha256 = "3b485a18390f407191d72b631b6865f80c5de063fd61a1442913e4d33dd22af4"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    admin.url = "/adm"
    admin.allowed = "admins"

    [resources.apt]
    packages = "mariadb-server, php8.2-mbstring, php8.2-gmp, php8.2-curl, php8.2-intl, php8.2-xmlrpc, php8.2-mysql, php8.2-gd, php8.2-xml, php8.2-cli, php8.2-zip, php8.2-bcmath"

    [resources.database]
    type = "mysql"
