packaging_format = 2

id = "phpbb"
name = "phpBB"
description.en = "Forum software that is easy to use, powerful, and highly customisable"
description.fr = "Forum facile à utiliser, puissant et hautement personnalisable"

version = "3.3.15~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0-only"
website = "http://www.phpbb.com/"
demo = "https://www.phpbb.com/demo/"
admindoc = "https://www.phpbb.com/support/docs/"
code = "https://github.com/phpbb/phpbb"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpbb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://download.phpbb.com/pub/release/3.3/3.3.15/phpBB-3.3.15.zip"
        sha256 = "3904cc6668ea52318867fec1f7fe8b9bc0bd5431da1df617aa5c43c092a44252"

        [resources.sources.fr]
        url = "https://github.com/qiaeru/phpbb-language-fr/archive/refs/tags/v4.14.0.zip"
        sha256 = "0516c92fa85b348b07cb6d700c389f2b9768e4eba13c315f6b965913e0c1f61e"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    admin.url = "/adm"
    admin.allowed = "admins"

    [resources.apt]
    packages = "mariadb-server, php8.3-mbstring, php8.3-gmp, php8.3-curl, php8.3-intl, php8.3-xmlrpc, php8.3-mysql, php8.3-gd, php8.3-xml, php8.3-cli, php8.3-zip, php8.3-bcmath"

    [resources.database]
    type = "mysql"
