#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

tmpdir="$(mktemp -d)"

ynh_setup_source --dest_dir="$tmpdir" --source_id=fr
cp -a "$tmpdir/language/fr" "$install_dir/language/fr"
cp -a "$tmpdir/styles/prosilver/theme/fr" "$install_dir/styles/prosilver/theme/fr"

ynh_safe_rm "$tmpdir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="install-config.yml.default" --destination="$install_dir/install/install-config.yml"

ynh_exec_as_app php${php_version} "$install_dir/install/phpbbcli.php" -q --no-interaction install "$install_dir/install/install-config.yml"

mv "$install_dir/install" "$install_dir/install_old"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

ynh_config_add --template="phpbb.cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
