#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=5

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

tmpdir="$(mktemp -d)"

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$tmpdir" --source_id=fr
cp -a "$tmpdir/language/fr" "$install_dir/language/fr"
cp -a "$tmpdir/styles/prosilver/theme/fr" "$install_dir/styles/prosilver/theme/fr" 
# Remove the tmp directory securely
ynh_secure_remove --file="$tmpdir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SETUP APPLICATION WITH CLI
#=================================================
ynh_script_progression --message="Configuring $app..." --weight=1

ynh_add_config --template="install-config.yml.default" --destination="$install_dir/install/install-config.yml"

ynh_exec_as "$app" php${phpversion} "$install_dir/install/phpbbcli.php" -q --no-interaction install "$install_dir/install/install-config.yml"

mv "$install_dir/install" "$install_dir/install_old"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

ynh_add_config --template="phpbb.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
