#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=5

ynh_setup_source --dest_dir="$install_dir" --keep="config.php images/ files/ store/"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=3

ynh_add_nginx_config

ynh_add_fpm_config

#=================================================
# UPGRADE APP
#=================================================
ynh_script_progression --message="Upgrading the $app..." --weight=1

ynh_exec_as $app php${phpversion} "$install_dir/bin/phpbbcli.php" --no-interaction db:migrate --safe-mode

if [ -e "$install_dir/install_old" ]; then
	ynh_secure_remove --file="$install_dir/install_old"
fi

if [ -e "$install_dir/install" ]; then
	ynh_exec_as $app mv "$install_dir/install" "$install_dir/install_old"
fi

#=================================================
# SETUP A CRON
#=================================================
ynh_script_progression --message="Setuping a cron..." --weight=1

ynh_add_config --template="../conf/phpbb.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
